# .goreleaser.yaml
version: 2
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - netbsd
      - openbsd
      - freebsd
      - plan9
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: netbsd
        goarch: arm64
      - goos: freebsd
        goarm: arm64
      - goos: plan9
        goarm: arm64
changelog:
  disable: false
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  abbrev: -1
release:
  footer: ""

