# .goreleaser.yaml
version: 2
builds:
  -
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X z.version={{.Version}} -X z.commit={{.Commit}} -X z.date={{.Date}}
    goos:
      - darwin
      - dragonfly
      - freebsd
      - linux
      - netbsd
      - openbsd
      - plan9
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: riscv64
      - goos: netbsd
        goarch: arm64
      - goos: netbsd
        goarch: riscv64
      - goos: freebsd
        goarm: arm64
      - goos: plan9
        goarm: arm
      - goos: plan9
        goarm: arm64
      - goos: plan9
        goarch: riscv64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: riscv64
changelog:
  disable: false
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  abbrev: -1
release:
  footer: ""

