Output zeit.gif

Set FontSize 16
Set Width 1280
Set Height 960
Set Padding 20
Set TypingSpeed 100ms

Type "zeit --help"
Sleep 500ms
Enter
Sleep 2s

Type "zeit"
Sleep 500ms
Enter
Sleep 1s

Type "zeit start work on project_one/task_one"
Sleep 500ms
Enter
Sleep 3s

Type "zeit"
Sleep 500ms
Enter
Sleep 2s

Type "zeit end"
Sleep 500ms
Enter
Sleep 1s

Type "zeit blocks this week"
Sleep 500ms
Enter
Sleep 3s

Type "zeit stats this week"
Sleep 500ms
Enter
Sleep 3s

